name: Simulator CI



on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: iverilog
        version: 1.0
          

    - name: run all
      run: make test_all
